# Generated by Django 5.2.6 on 2025-09-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Insira o nome do jogo', max_length=256)),
                ('ano', models.IntegerField(help_text='Insira o ano do jogo')),
                ('empresa', models.CharField(help_text='Insira o nome da empresa', max_length=256)),
            ],
        ),
    ]
