# Generated by Django 5.2.6 on 2025-09-20 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogo",
            name="ano",
            field=models.IntegerField(
                help_text="Insira o ano do jogo",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
    ]
