# Generated by Django 5.2.6 on 2025-09-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0002_alter_jogo_ano"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogo",
            name="capa",
            field=models.ImageField(default=0, upload_to="images/"),
            preserve_default=False,
        ),
    ]
