# Generated by Django 5.2.6 on 2025-09-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0003_jogo_capa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogo",
            name="capa",
            field=models.CharField(help_text="Insira a capa do jogo", max_length=256),
        ),
    ]
